# Generated by Django 5.0.6 on 2024-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('des', models.TextField(max_length=100)),
            ],
        ),
    ]
