# Generated by Django 5.0.6 on 2024-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='des',
        ),
        migrations.AddField(
            model_name='subject',
            name='std',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
